# Generated by Django 5.2.3 on 2025-06-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
