# Generated by Django 5.2.3 on 2025-06-29 08:35

import django.db.models.deletion  # Import deletion behaviors for model relationships
from django.conf import settings  # Import Django settings (for AUTH_USER_MODEL)
from django.db import migrations, models  # Import migration and model classes

# Define a migration class for database schema changes
class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),  # Depends on the initial migration of maintenance app
        ('properties', '0002_initial'),  # Depends on the initial migration of properties app
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Depends on the user model (customizable)
    ]

    operations = [
        # Create the MaintenanceChat model/table
        migrations.CreateModel(
            name='MaintenanceChat',  # Model name
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Primary key field
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Timestamp when chat is created
                ('tenant', models.ForeignKey(  # Foreign key to user (tenant)
                    on_delete=django.db.models.deletion.CASCADE,  # Delete chat if tenant is deleted
                    related_name='tenant_chats',  # Related name for reverse lookup from user
                    to=settings.AUTH_USER_MODEL  # Reference to user model
                )),
                ('unit', models.ForeignKey(  # Foreign key to unit
                    on_delete=django.db.models.deletion.CASCADE,  # Delete chat if unit is deleted
                    related_name='chats',  # Related name for reverse lookup from unit
                    to='properties.unit'  # Reference to Unit model in properties app
                )),
            ],
        ),
        # Create the MaintenanceMessage model/table
        migrations.CreateModel(
            name='MaintenanceMessage',  # Model name
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Primary key field
                ('message', models.TextField()),  # Message content
                ('timestamp', models.DateTimeField(auto_now_add=True)),  # Timestamp when message is created
                ('chat', models.ForeignKey(  # Foreign key to MaintenanceChat
                    on_delete=django.db.models.deletion.CASCADE,  # Delete message if chat is deleted
                    related_name='messages',  # Related name for reverse lookup from chat
                    to='maintenance.maintenancechat'  # Reference to MaintenanceChat model
                )),
                ('sender', models.ForeignKey(  # Foreign key to user (sender)
                    on_delete=django.db.models.deletion.CASCADE,  # Delete message if sender is deleted
                    to=settings.AUTH_USER_MODEL  # Reference to user model
                )),
            ],
        ),
    ]
