# Generated by Django 5.2.3 on 2025-06-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancechat_maintenancemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Contractor or person assigned', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
