# Generated by Django 5.2.3 on 2025-06-30 17:12  # Auto-generated by Django's migration system

from django.db import migrations, models  # Import migration and model classes from Django

class Migration(migrations.Migration):  # Define a new migration class

    dependencies = [
        ('maintenance', '0003_maintenancechat_maintenancemessage'),  # This migration depends on the previous one
    ]

    operations = [
        migrations.AddField(  # Add a new field to a model
            model_name='maintenancerequest',  # The model to alter
            name='assigned_to',  # Name of the new field
            field=models.CharField(  # Field type: character field
                blank=True,  # Field can be left blank in forms
                help_text='Contractor or person assigned',  # Help text for the field
                max_length=100,  # Maximum length of 100 characters
                null=True  # Field can be null in the database
            ),
        ),
        migrations.AddField(  # Add another new field
            model_name='maintenancerequest',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(  # Field type: small positive integer
                blank=True,  # Can be left blank in forms
                help_text='1-5 stars',  # Help text for the field
                null=True  # Can be null in the database
            ),
        ),
        migrations.AddField(  # Add another new field
            model_name='maintenancerequest',
            name='tenant_confirmed',
            field=models.BooleanField(  # Field type: boolean (True/False)
                default=False  # Default value is False
            ),
        ),
        migrations.AddField(  # Add another new field
            model_name='maintenancerequest',
            name='tenant_feedback',
            field=models.TextField(  # Field type: text (unlimited length)
                blank=True,  # Can be left blank in forms
                null=True  # Can be null in the database
            ),
        ),
    ]
