# Generated by Django 5.2.3 on 2025-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], max_length=10)),
                ('transaction_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
