# Generated by Django 5.2.3 on 2025-06-29 07:45  # Auto-generated by Django's migration system

import django.db.models.deletion  # Import deletion behaviors for model relationships
from django.conf import settings  # Import Django settings (for AUTH_USER_MODEL)
from django.db import migrations, models  # Import migration and model utilities

class Migration(migrations.Migration):  # Define a migration class inheriting from Django's Migration

    initial = True  # Marks this as an initial migration for this app

    dependencies = [
        ('payments', '0001_initial'),  # Depends on the initial migration of the payments app
        ('properties', '0001_initial'),  # Depends on the initial migration of the properties app
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Depends on the user model (customizable)
    ]

    operations = [
        migrations.AddField(  # Operation to add a field to a model
            model_name='payment',  # The model to which the field is added
            name='confirmed_by',  # Name of the new field
            field=models.ForeignKey(  # Define a ForeignKey relationship
                blank=True,  # Field is allowed to be blank in forms
                null=True,  # Field is allowed to be null in the database
                on_delete=django.db.models.deletion.SET_NULL,  # Set to NULL if the related user is deleted
                to=settings.AUTH_USER_MODEL  # Reference to the user model
            ),
        ),
        migrations.AddField(  # Operation to add another field
            model_name='payment',  # The model to which the field is added
            name='lease',  # Name of the new field
            field=models.ForeignKey(  # Define a ForeignKey relationship
                on_delete=django.db.models.deletion.CASCADE,  # Delete payments if the related lease is deleted
                related_name='payments',  # Allows reverse lookup from Lease to its payments
                to='properties.lease'  # Reference to the Lease model in the properties app
            ),
        ),
    ]
